### ISSUE TITLE
Please upgrade to Click 7

### ISSUE THREAD

**Issue by hartwork** [costela/wile#36]
Hi!

In an environment with other packages around Wile, e.g. a Linux distribution, users want to be able to use Click 7 but use of Wile keeps them from upgrading. Any chance you could update Wile to work with Click `>=7` or both `<7` and `>=7`? The current `< 7.0` is not a good long-term solution.

Thanks and best, Sebastian

**Comment by costela** [comment]
Hi @hartwork 

Just pushed the small changes that should (hopefully) fix this. However: I haven't been using or maintaining this tool for a while and it currently lacks ACMEv2 support (see #37).
Maybe it would be a good idea to switch to a better maintained tool?

**Comment by hartwork** [comment]
> Just pushed the small changes that should (hopefully) fix this.

Thank you!
