### ISSUE TITLE
Code cleanup and PEP 8 Style Guide

### ISSUE THREAD

**Issue by lumatijev** [costela/wile#6]
Are you interested in cleaning up source code and styling it according to PEP 8 Style Guide?

I can make few pull request if you are interested.

**Comment by costela** [comment]
Yup, that's definitely on the TODO list, but hold off on the PRs because I'm also working on it, as time allows! :wink:  (it should be pushed in the next few days, together with some belated unittests; so much for TBD... :wink: )

**Comment by lumatijev** [comment]
Nice to hear that. If you will need help with refactoring I am willing to give you a hand (as time allows).
